<?php

/**
 * @file
 * Hooks and alters for the charity -> salesforce transition.
 */

/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter().
 *
 * @see \Drupal\unhcr_commerce\Plugin\Field\FieldWidget:UnhcrOptionsSelectWidget()
 */
function unhcr_salesforce_charity_field_widget_unhcr_options_select_form_alter(&$element, &$form_state, $context) {
  $element['#disabled'] = TRUE;
  $element['#suffix'] = t('Deprecated field');
  $element['#access'] = FALSE;
}
