<?php

/**
 * @file
 * Hooks and alters for the Salesforce integration.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function unhcr_salesforce_web_form_unhcr_salesforce_alter(&$form, &$form_state, $form_id) {
  try {
    $form['salesforce_gift_campaign'] = [
      '#type' => 'select',
      '#title' => t('Select the campaign for the giftshop items.'),
      '#default_value' => \Drupal::config('unhcr_salesforce.settings')->get('salesforce_gift_campaign'),
      '#empty_option' => t('- Please select -'),
      '#required' => TRUE,
      '#options' => \Drupal::service('unhcr_salesforce.client')->getCampaignOptions(),
    ];
    $form['actions']['submit']['#submit'][]  = 'unhcr_salesforce_web_settings_form_submit';
  }
  catch (\Exception $e) {
    watchdog_exception('unhcr_salesforce_web', $e);
  }
}

/**
 * Submit callback for the settings form to save.
 */
function unhcr_salesforce_web_settings_form_submit(array $form, FormStateInterface $form_state) {
  if ($form_state->hasValue('salesforce_gift_campaign')) {
    $config = \Drupal::configFactory()->getEditable('unhcr_salesforce.settings');
    $config->set('salesforce_gift_campaign', $form_state->getValue('salesforce_gift_campaign'));
    $config->save();
  }
}
